### ISSUE TITLE
Can not remove node in spline vis.

### ISSUE THREAD

**Issue by S3BASTI3N** [pkok/behavior-engine#2]
Spamming delete, while a node is selected does not do anything, both wile in focus or not.

**Comment by pkok** [comment]
Please include browser name, browser version and OS in your report.

**Comment by S3BASTI3N** [comment]
Firefox, 47, Ubuntu 14.04, favorite color: blue

**Comment by pkok** [comment]
I'm running the visualization in the same mode, but cannot confirm the bug.

After a personal chat, you told me the bug that you can remove points on the end of the spline. I made a separate bug for this, please see #4 .

**Comment by m0re4u** [comment]
Cannot remove nodes on Google Chrome Version 51.0.2704.103 (64-bit) on Ubuntu 14.04

**Comment by pkok** [comment]
Chrome is not supported. :kissing_heart:

**Comment by pkok** [comment]
Problem solved for @S3BASTI3N
