### ISSUE TITLE
Visualisation does not update when range or utility score is adjusted

### ISSUE THREAD

**Issue by S3BASTI3N** [pkok/behavior-engine#3]
As of now, when the range or utility score of a consideration are adjusted the plot (and nodes) stay the same. When the downloading and then uploading the Rules, the nodes are drawn using the old range and or utility score.

Suggestion: always draw vis. in range 0-1 for x and y and only use the utility score and range when downloading/uploading the rules.

Firefox, 47, Ubuntu 14.04, favorite color: blue

**Comment by pkok** [comment]
Known problem, will work on this.
